### ISSUE TITLE
Better project tracking and promotion on codeforseattle.org

### ISSUE THREAD

**Issue by sethvincent** [codeforseattle/codeforseattle.github.com#20]
The [projects page](http://codeforseattle.org/projects/) is out of date. Let's fix that.

A few ideas:

### Put the list in the repository
We're using Jekyll in this repository, so we could make use of either [files in a _data folder](http://jekyllrb.com/docs/datafiles/) or a [projects collection](http://jekyllrb.com/docs/collections/) for tracking projects directly in this repository. It might be best for each project to have its own file. For now I've put a [projects.yml file in the _data directory](https://github.com/codeforseattle/codeforseattle.github.com/blob/master/_data/projects.yml), and we can break it up into separate files or otherwise make changes.

### Put projects on the front page
It would be great to have a few featured projects on the front page of the site.

### Project list should be compatible with the CFAPI
Code for America has an API for brigades & projects. Our project list needs to be in a format that is consumable by CFAPI. Learn more about how it works here: https://github.com/codeforamerica/cfapi

### Surface active projects
We should make the full list of projects filterable, and by default filter out projects that are not currently being worked on. We should not hesitate to aggressively curate the active projects list to make sure there's interesting projects being highlighted.

### Maybe codeforseattle.org/projects should have:
- featured projects
- information about what it means to be working on a project with/at code for seattle
- resources people can access through code for seattle
- a big link to codeforseattle.org/projects/list which is the full, filterable list of projects

### A guide for getting started leading a project
I recently started the guides section of the website. A nice guide to have would be the basics of leading a project that's supported by / worked on at code for seattle events. This would include things like how to get the project listed on codeforseattle.org, as well as useful resources, and maybe a few suggestions for tools & how to find team members.

### What else?
I'm sure there are other things we could do! I'd like to hear your ideas. And I'd be veeeeery happy to have help implementing the above changes.

**Comment by sethvincent** [comment]
As of commit 4bd904b97ee914b17d7fe9f01cd63123daab8747 the projects list is now generated based on the projects.yml file in the _data folder: https://github.com/codeforseattle/codeforseattle.github.com/blob/master/_data/projects.yml

Next I'll be writing a guide that explains how people can add their project.

The projects page can definitely still use some work though. Improved styles would be nice, and a simplified set of properties for each project would be cool too. Also we need a screenshot or photo for every project.

**Comment by willscott** [comment]
:+1:

**Comment by sethvincent** [comment]
There's now a guide for adding projects to the project list: http://codeforseattle.org/guides/project-list

Closing this and opening a couple more specific issues about projects.
